### ISSUE TITLE
l10ignore does not work for /app/vendor/pdfjs/lib/pdf.worker.js

### ISSUE THREAD

**Issue by rakekniven** [e-alfred/epubreader#15]
There are strings at Transifex which should not be there.

e.g. https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/288864401?q=translated_after%3A2020-04-01+reviewed%3Ano

The file containing the string (pdf.worker.js) is listed in `.l10nignore` but the strings are still there.

@morrisjobke Do you have any idea?

**Comment by MorrisJobke** [comment]
Not really - first I thought it might be because of a mistyped character but it seems fine.

**Comment by e-alfred** [comment]
This is a very strange issue. I am not sure if something can be changed from the repository side, if you can help me point out what to change I would really appreciate that.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/epubreader/pull/17, thanks @rakekniven! Small mistakes causing much nuisance. :grimacing:
