### ISSUE TITLE
Certificate "4356" has been revoked 

### ISSUE THREAD

**Issue by svankan** [e-alfred/epubreader#16]
I uninstalled Reader (in Nextcloud 19.0.2) 1.4.2 and when I tried to download and enable it again I got this error message.
"An error occured during the request. Unable to proceed.
Certificate "4356" has been revoked"

Upgraded from Nextcloud 18.0.8 to 19.0.2 and epubreader was working until I removed the app and I tried to reinstall.

Server setup:
Ubuntu 18.04.5 LTS
Nginx 1.19.2
PHP 7.3.21
Nextcloud 19.0.2

**Comment by e-alfred** [comment]
Thanks for the information, I have to create a new release with the new certificate: https://github.com/nextcloud/app-certificate-requests/pull/293

**Comment by human-blip** [comment]
When will the new release be created? I am seeing this problem too.

**Comment by bohica70** [comment]
First off. Great work!!. Do you have any idea when the certificate issue will be resolved?

**Comment by infidelus** [comment]
Also seeing this error after reinstalling NC19.

**Comment by KlomDark** [comment]
Any news on this issue? I am severely missing this app and can't wait til it's back! Is there anything I can do to help? Jonesing on reading my ebooks! :)

**Comment by gitaarik** [comment]
What's needs to happen? Making a new release with the new certificate? How does that process go?

**Comment by beankylla** [comment]
Also being affected by this issue.
is there anything i can do to help ? :)

**Comment by klorydryk** [comment]
Same issue :(
What is the problem?

**Comment by dgedgedge** [comment]
FYI: It it may help:

See: https://github.com/nextcloud/files_texteditor/issues/271
And: https://github.com/nextcloud/server/issues/20674

**Comment by e-alfred** [comment]
Sorry for the delay, Nextcloud issued me with a faulty certificate (see https://github.com/nextcloud/app-certificate-requests/pull/293), this is fixed now with release 1.4.3.

**Comment by bohica70** [comment]
Just tried to install this and received:

Unable to proceed.
Index name "oc_reader_preferences"."reader_preferences_file_id_index" is 
too long.

------ Original Message ------

**Comment by KlomDark** [comment]
> Just tried to install this and received: Unable to proceed. Index name "oc_reader_preferences"."reader_preferences_file_id_index" is too long.

Interesting, I just installed it and it works for me without the issue you are experiencing.

I'm sorry for you, but YAY I can read my ebooks again! :)

**Comment by klorydryk** [comment]
> Just tried to install this and received: Unable to proceed. Index name "oc_reader_preferences"."reader_preferences_file_id_index" is too long.

Same for me, nextcloud 19.0.4

**Comment by infidelus** [comment]
Also seeing this message on 19.04

**Comment by gitaarik** [comment]
Yes, also getting this error when I try to install 1.4.3 on Nextcloud 19.0.4:

![image](https://user-images.githubusercontent.com/2470302/96479139-254b7680-11fe-11eb-8e10-f4fdff9cda7c.png)

**Comment by dgedgedge** [comment]
FYI. I have 19.04 nextcloud.
I did deinstall the previous relaease with occ.
Even if not seen installed with HMI, it was partly installed.

I also have the 2 releases in the app store. 
The old one called "Reader (ebook Reader)
The new one called "EPUB/CBZ/PDF ebook reader " 

It was a quite confusing for me.
Once de-installed and choosing the right application, installation worked fine.
The application worke fine also.

Thanks for all.
Regards.

**Comment by infidelus** [comment]
I didn't have the previous release installed as I did a fresh Nextcloud install recently and the certificate error stopped me installing, so there's nothing to uninstall on my instance.

**Comment by emansije** [comment]
> Yes, also getting this error when I try to install 1.4.3 on Nextcloud 19.0.4:
> 
> ![image](https://user-images.githubusercontent.com/2470302/96479139-254b7680-11fe-11eb-8e10-f4fdff9cda7c.png)

`Error: Index name "oc_reader_preferences"."reader_preferences_file_id_index" is too long.`

I'm getting the same error. The app is installed, but that error pops up if I try to activate it.

**Comment by gitaarik** [comment]
I just got an update and that one seems to work all good :smiley::+1:

**Comment by klorydryk** [comment]
Yes it's fine for me, thanks!
