### ISSUE TITLE
Nextcloud 21 - support

### ISSUE THREAD

**Issue by celogeek** [e-alfred/epubreader#30]
Hi,

Thanks for this plugin!

I received a NC 21 update recently, and the app is disabled now.

Here the result of the app:check:

```
occ app:check epubreader
Analysing /var/lib/nextcloud/apps/epubreader/ajax/personal.php
 3 errors
    line   15: OC_JSON - Static method of deprecated class must not be called
    line   16: OC_JSON - Static method of deprecated class must not be called
    line   28: OC_JSON - Static method of deprecated class must not be called
Analysing /var/lib/nextcloud/apps/epubreader/appinfo/app.php
 2 errors
    line   22: OCP\App - Static method of deprecated class must not be called
    line   22: OCP\App::registerPersonal - Method of deprecated class must not be called
Analysing /var/lib/nextcloud/apps/epubreader/lib/Controller/PageController.php
 1 errors
    line  148: == - is discouraged
Analysing /var/lib/nextcloud/apps/epubreader/lib/Hooks.php
 1 errors
    line   68: == - is discouraged
Analysing /var/lib/nextcloud/apps/epubreader/lib/config.php
 4 errors
    line   28: OCP\User - Static method of deprecated class must not be called
    line   28: OCP\User::getUser - Method of deprecated class must not be called
    line   39: OCP\User - Static method of deprecated class must not be called
    line   39: OCP\User::getUser - Method of deprecated class must not be called
App is not compliant
```

Can you update your app to be compatible with NC21 ?

Thanks !

**Comment by benjamin-luker** [comment]
> Hi,
> 
> Thanks for this plugin!
> 
> I received a NC 21 update recently, and the app is disabled now.
> 
> Here the result of the app:check:
> 
> ```
> occ app:check epubreader
> Analysing /var/lib/nextcloud/apps/epubreader/ajax/personal.php
>  3 errors
>     line   15: OC_JSON - Static method of deprecated class must not be called
>     line   16: OC_JSON - Static method of deprecated class must not be called
>     line   28: OC_JSON - Static method of deprecated class must not be called
> Analysing /var/lib/nextcloud/apps/epubreader/appinfo/app.php
>  2 errors
>     line   22: OCP\App - Static method of deprecated class must not be called
>     line   22: OCP\App::registerPersonal - Method of deprecated class must not be called
> Analysing /var/lib/nextcloud/apps/epubreader/lib/Controller/PageController.php
>  1 errors
>     line  148: == - is discouraged
> Analysing /var/lib/nextcloud/apps/epubreader/lib/Hooks.php
>  1 errors
>     line   68: == - is discouraged
> Analysing /var/lib/nextcloud/apps/epubreader/lib/config.php
>  4 errors
>     line   28: OCP\User - Static method of deprecated class must not be called
>     line   28: OCP\User::getUser - Method of deprecated class must not be called
>     line   39: OCP\User - Static method of deprecated class must not be called
>     line   39: OCP\User::getUser - Method of deprecated class must not be called
> App is not compliant
> ```
> 
> Can you update your app to be compatible with NC21 ?
> 
> Thanks !

+1 on desire for NC21 support - just installed my first NC instance and this looks amazing. Following closely!

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/epubreader/releases/tag/1.4.6.
